builds:
  - binary: teler-proxy
    main: cmd/teler-proxy/main.go
    ldflags:
      - -s -w -X github.com/kitabisa/teler-proxy/common.Version=v{{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    env:
      - CGO_ENABLED=1
