builds:
  - binary: teler-proxy
    main: cmd/teler-proxy/main.go
    ldflags:
      - -s -w -X github.com/kitabisa/teler-proxy/common.Version=v{{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    env:
      - CGO_ENABLED=1
      - CC_darwin_amd64=o64-clang
      - CCX_darwin_amd64=o64-clang+
      - CC_darwin_arm64=aarch64-apple-darwin20.2-clang
      - CCX_darwin_arm64=aarch64-apple-darwin20.2-clang++
      - CC_windows_amd64=x86_64-w64-mingw32-gc
      - CCX_windows_amd64=x86_64-w64-mingw32-g++
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CCX={{ index .Env (print "CCX_" .Os "_" .Arch) }}'
  
archives:
  - id: binary
    format_overrides:
      - goos: windows
        format: zip