name: Auto Merge PR

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened]
  pull_request_review:
    types: [submitted]
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: teler-sh/actions/auto-merge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}