name: "Generate PGO"

on:
  push:
    branches:
      - master
    paths:
      - "pkg/tunnel/**.go"
      - "go.*"
  workflow_dispatch:

env:
  PGO_FILE: "default.pgo"
  PGO_BRANCH: "pgo"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: '**/go.sum'
      - run: make pprof && cp ${{ env.PGO_FILE }} /tmp/
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.PGO_BRANCH }}
      - run: |
          git rm --cached ${{ env.PGO_FILE }}
          cp /tmp/${{ env.PGO_FILE }} .
      - if: ${{ success() || failure() }}
        run: |
          git config --local user.email "ghost@users.noreply.github.com"
          git config --local user.name "ghost"
          git add ${{ env.PGO_FILE }}
          git commit -m "build(pgo): generate default PGO profile :robot:"
          git push origin ${{ env.PGO_BRANCH }}
