name: "Tests"

on:
  push:
    branches:
      - master
      - wip
    paths:
      - "**.go"
      - "go.mod"
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - uses: actions/checkout@v3
      - name: Vetting
        run: make vet
      - name: Build
        run: make build
      - name: Clean up
        run: make clean

  golangci:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=5m
        
  semgrep:
    runs-on: ubuntu-latest
    needs: tests
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
           SEMGREP_RULES: auto

  codeql:
    needs: tests
    uses: ./.github/workflows/codeql.yaml
